 interface Account {
    void deposit(in unsigned long amount );
    void withdraw(in unsigned long amount );
    long balance();
  };

  interface Bank {
    //String Name;
    Account create(out long id);
    void destroy(in Account a);
    Account lookup(in long id);
    Account move(in Bank target, in Account a);
  };						
