
/**
* EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* mercredi 24 octobre 2012 16 h 35 CEST
*/


// Echo.idl
public interface EchoOperations 
{    
    org.omg.CORBA.Any echoAny (org.omg.CORBA.Any x);
} // interface EchoOperations
