
/**
* AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* lundi 12 novembre 2012 17 h 24 CET
*/

public interface AccountOperations 
{
  void deposit (int amount);
  void withdraw (int amount);
  int balance ();
  int getId ();
} // interface AccountOperations
