
/**
* BankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* lundi 12 novembre 2012 17 h 24 CET
*/

public interface BankOperations 
{
  Account create (org.omg.CORBA.IntHolder id);
  void destroy (Account a);
  Account move (Bank target, Account a);
  Account lookup (int id);
} // interface BankOperations
